# Generated by Django 4.2.4 on 2023-08-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_intrest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('desc', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
