# Generated by Django 4.2.4 on 2023-08-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_summary_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('p1', models.CharField(max_length=120)),
                ('p2', models.CharField(max_length=120)),
                ('p3', models.CharField(max_length=120)),
            ],
        ),
    ]
