# Generated by Django 4.2.4 on 2023-08-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=120)),
                ('image', models.FileField(max_length=255, null=True, upload_to='projects/')),
                ('link', models.CharField(max_length=120)),
            ],
        ),
    ]
